services:
  ai:
    build:
      context: ai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEWS_IMPACT_LLM=${NEWS_IMPACT_LLM}
      - COMMAND_PARSE_LLM=${COMMAND_PARSE_LLM}
      - BACKEND_API_URL=${BACKEND_API_URL}
      - MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE=${MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE}
      - NEWS_IMPACT_VARIANT=${NEWS_IMPACT_VARIANT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_PORT=5672
      - RABBITMQ_HOST=rabbitmq
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - ./ai:/app
    networks:
      - tarantula

  postgres-db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: radomDB
    ports:
      - "5432:5432"
    networks:
      - tarantula
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/radomDB
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ARTICLE_SCHEDULER_FIXED_RATE=${ARTICLE_SCHEDULER_FIXED_RATE}
      - ARTICLE_SCHEDULER_CRON=${ARTICLE_SCHEDULER_CRON}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - ai
    networks:
      - tarantula

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=${FRONTEND_API_URL}
      - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - tarantula

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./ai/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - tarantula

  worker:
    build:
      context: ai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEWS_IMPACT_LLM=${NEWS_IMPACT_LLM}
      - COMMAND_PARSE_LLM=${COMMAND_PARSE_LLM}
      - BACKEND_API_URL=${BACKEND_API_URL}
      - MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE=${MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE}
      - NEWS_IMPACT_VARIANT=${NEWS_IMPACT_VARIANT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - rabbitmq
      - redis
    ports: []
    command: poetry run dramatiq app.tasks --processes 1 --threads 1
    volumes:
      - ./ai:/app
    networks:
      - tarantula

  redis:
    image: redis:7-alpine
    command:
      - /bin/sh
      - -c
      - redis-server --save 20 1 --loglevel warning --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - tarantula
    expose:
      - "6379"

networks:
  tarantula:

volumes:
  postgres_data:
  frontend_node_modules:
  rabbitmq_data:
  redis_data: