version: '3.8'

services:
  ai:
    build:
      context: ai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
    networks:
      - tarantula

networks:
  tarantula:
