version: '3.8'

services:
  ai:
    build:
      context: ai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
    networks:
      - tarantula

  postgres-db:
    image: postgres:17
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: radomDB
    ports:
      - "5432:5432"
    networks:
      - tarantula
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/radomDB
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - tarantula

networks:
  tarantula:

volumes:
  postgres_data:
