INSERT INTO stocks (id, symbol, name, description, ekd, address, country, exchange)
VALUES
    (gen_random_uuid(), 'CDR', 'CD PROJEKT RED SA', 'CD PROJEKT is a leading video game developer known for creating successful titles such as The Witcher series and Cyberpunk 2077.', 'Video Game Development', 'Warsaw', 'PL', 'GPW'),
    (gen_random_uuid(), 'KGHM', 'KGHM Polska Miedź SA', 'KGHM is one of the world’s largest copper producers, also engaged in the mining of silver and other precious metals.', 'Mining (Copper and Precious Metals)', 'Lubin', 'PL', 'GPW'),
    (gen_random_uuid(), 'PKN', 'PKN ORLEN SA', 'PKN ORLEN is one of the largest petrochemical companies in Central and Eastern Europe, active in the fuel, chemical, and energy sectors.', 'Petrochemicals & Energy', 'Płock', 'PL', 'GPW'),
    (gen_random_uuid(), 'GOGL', 'Alphabet Inc.', 'Google, now Alphabet Inc., is an American multinational technology company known for its search engine and services such as cloud computing, advertising, hardware, and software.', 'Technology & Internet Services', 'Mountain View', 'US', 'NYSE'),
    (gen_random_uuid(), 'AAPL', 'Apple Inc.', 'Apple Inc. is an American multinational technology company known for designing and manufacturing consumer electronics, software, and digital services.', 'Consumer Electronics & Software', 'Cupertino', 'US', 'NYSE'),
    (gen_random_uuid(), 'META', 'Meta Platforms, Inc.', 'Facebook, now Meta Platforms, is an American technology company specializing in social media services, internet advertising, and developing virtual reality technologies.', 'Social Media & Internet Advertising', 'Menlo Park', 'US', 'NYSE'),
    (gen_random_uuid(), 'CCJ', 'Cameco Corporation', 'Cameco is a Canadian company engaged in the mining and production of uranium, supplying the material for nuclear power plants worldwide.', 'Uranium Mining', 'Saskatoon', 'CA', 'NYSE'),
    (gen_random_uuid(), 'RIO', 'Rio Tinto Group', 'Rio Tinto is a multinational corporation engaged in mining and refining a range of minerals and metals, including iron ore, copper, and aluminum.', 'Mining & Natural Resources', 'London', 'GB', 'ASX'),
    (gen_random_uuid(), 'VEEV', 'Veeva Systems Inc.', 'Veeva Systems is an American company that provides cloud-based software solutions for the pharmaceutical and biotechnology industries.', 'Cloud Software (Pharmaceuticals & Biotechnology)', 'Pleasanton', 'US', 'NYSE'),
    (gen_random_uuid(), 'JSW', 'Jastrzębska Spółka Węglowa SA', 'JSW Group is the largest producer of high-quality hard coking coal in the European Union and a leading manufacturer of steel.', 'Coal Mining & Steel Manufacturing', 'Jastrzębie-Zdrój', 'PL', 'GPW');
