spring:
  profiles:
    active: dev
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/radomDB
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  hikari:
    maximum-pool-size: 10
    pool-name: HikariCP
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  doc:
    api-docs:
      enabled: true
      path: /v3/api-docs
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
      doc-expansion: none
  show-actuator: true

jwt:
  secret: wartosc_domyslna_tylko_dla_dev_nie_produkcja_klucza_sekretnego_ściśle_strzeżonego
vapid:
  public.key: BKpBiJpEMiFP_DHHjoQuulIVbVPCFS0RrOkIdh3EgEO_awvW7_LQA4iU2x5qhCeHemWQHdu4GWpakdLoqiBp1WA
  private.key: Kgosx01sBrGh0FazCqS6hRVG-inT4vhnTtk2-Bi9lHk
  subject: mailto:dummy@yourdomain.com

article:
  scheduler:
    fixed-rate: 10000000
    cron: 0 0 8 * * *