name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Init .env
        run: cp .env.example .env
      - name: Start Docker Compose services
        run: docker compose up -d

      - name: Check service health
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
          max-retries: 6
          retry-interval: 5
          compose-file: "compose.yaml"
          skip-exited: "false"
          skip-no-healthcheck: "false"
